#!/bin/bash
set -e

REMOTE_REPO=https://github.com/woky/rchain-logstash
REPO=/opt/rchain-logstash
ID=rchain-logstash

CRON_LINK=/etc/cron.hourly/$ID-update-run-setup
STATE_FILE=/var/cache/$ID-setup-gitrev

GIT_CRYPT_KEY_FILE=/root/rchain-sre.git-crypt-key

############################################################

if [[ ! -d $REPO ]]; then
	export DEBIAN_FRONTEND=noninteractive
	apt update
	apt install -y --no-install-recommends git git-crypt cron
	git clone $REMOTE_REPO $REPO
fi

cd $REPO

if ! git pull; then
	echo "Failed to pull changes to $REPO" >&2
	git status >&2
fi

if [[ -e $STATE_FILE ]]; then
	curr_gitrev="$(git rev-parse --short HEAD)"
	last_gitrev="$(cat $STATE_FILE)"
	if [[ "$last_gitrev" == "$curr_gitrev" ]]; then
		exit 0
	fi
fi

if [[ -e .git-crypt ]]; then
	( umask 077 && git-crypt unlock $GIT_CRYPT_KEY_FILE )
fi

if [[ -n "$CRON_LINK" && "$(readlink $CRON_LINK)" != $REPO/host-update-run-setup ]]; then
	ln -s $REPO/host-update-run-setup $CRON_LINK
fi

############################################################

ret=0
flock -x -n -E 77 $STATE_FILE ./host-setup || ret=$?
case $ret in
	0)  echo "$curr_gitrev" >$STATE_FILE ;;
	77) echo "Another instance is running" >&2 ;;
esac
exit $ret
