#!/bin/bash -e
cd "$(dirname $0)"

export DEBIAN_FRONTEND=noninteractive
apt update -q
apt install -yq wget apt-transport-https gnupg2 openjdk-8-jre-headless \
	openssh-client

wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" \
	> /etc/apt/sources.list.d/elastic-6.x.list
apt update -q
apt install -yq logstash

if ! grep -q '^config.reload.automatic:' /etc/logstash/logstash.yml; then
	echo 'config.reload.automatic: true' >>/etc/logstash/logstash.yml
fi
if ! grep -q '^config.reload.interval:' /etc/logstash/logstash.yml; then
	echo 'config.reload.interval: 5s' >>/etc/logstash/logstash.yml
fi
/usr/share/logstash/bin/logstash-plugin install logstash-output-nagios
install -C -m644 rnode-pipeline.conf -t /etc/logstash/conf.d

install -m700 -d /root/.ssh
install -C -m600 secrets/id_rsa -t /root/.ssh/
install -C -m644 secrets/id_rsa.pub -t /root/.ssh/
install -C -m755 nagios-ssh-cmd -t /usr/local/bin/
install -C -m644 nagios-ssh-cmd.rc -t /etc
install -C -m644 nagios-ssh-cmd.service /etc/systemd/system

systemctl enable nagios-ssh-cmd.service logstash
systemctl restart nagios-ssh-cmd.service logstash
