#!/bin/bash -e

export DEBIAN_FRONTEND=noninteractive
apt update
apt install -y wget apt-transport-https gnupg2 openjdk-8-jre-headless

wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" \
	> /etc/apt/sources.list.d/elastic-6.x.list
apt update
apt install -y logstash

if ! grep -qx 'config.reload.automatic: true' /etc/logstash/logstash.yml; then
	echo 'config.reload.automatic: true' >>/etc/logstash/logstash.yml
fi

if ! grep -qx 'config.reload.interval: 5s' /etc/logstash/logstash.yml; then
	echo 'config.reload.interval: 5s' >>/etc/logstash/logstash.yml
fi

install -C -m644 rnode-pipeline.conf -t /etc/logstash/conf.d
systemctl enable logstash
systemctl restart logstash
