#!/bin/bash -e
cd "$(dirname $0)"

export DEBIAN_FRONTEND=noninteractive
apt update -q
apt install -yq wget apt-transport-https gnupg2 openjdk-8-jre-headless

wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" \
	> /etc/apt/sources.list.d/elastic-6.x.list
apt update -q
apt install -yq logstash

if ! grep -q '^config.reload.automatic:' /etc/logstash/logstash.yml; then
	echo 'config.reload.automatic: true' >>/etc/logstash/logstash.yml
fi
if ! grep -q '^config.reload.interval:' /etc/logstash/logstash.yml; then
	echo 'config.reload.interval: 5s' >>/etc/logstash/logstash.yml
fi
install -C -m644 rnode-pipeline.conf -t /etc/logstash/conf.d
install -C -m644 pipelines.yml -t /etc/logstash/

systemctl enable logstash
systemctl restart logstash
